# Generated by Django 5.1.5 on 2025-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='events.event'),
        ),
    ]
