# Generated by Django 5.1.5 on 2025-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_tasks/default.jpg', null=True, upload_to='event_tasks'),
        ),
    ]
